apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-service
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup nginxsvc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done" ]
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80