version: '3.5'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '142yfdwzfi'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Zaq12wsx'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /home/centos/mysql_test/data/db:/var/lib/mysql