{
 "title": "Homework",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPULa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_load15{instance=\"localhost:9100\",job=\"netbox_scripter_localhost\"})",
     "legendFormat": "CPULA - 15"
    },
    {
     "expr": "(node_load1{instance=\"localhost:9100\",job=\"netbox_scripter_localhost\"})",
     "legendFormat": "CPULA - 1"
    },
    {
     "expr": "(node_load5{instance=\"localhost:9100\",job=\"netbox_scripter_localhost\"})",
     "legendFormat": "CPULA - 5"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"netbox_scripter_localhost\"}"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"netbox_scripter_localhost\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "IDLE CPU"
    }
   ]
  },
  {
   "title": "Free mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\",job=\"netbox_scripter_localhost\",device!~\"/dev/vda2\"}"
    }
   ]
  }
 ]
}