apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: network-multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: vol
              mountPath: /multitool
      volumes:
        - name: vol
          hostPath:
            path: /var/log/